voj:
  jwt:
    secret: voj-secret-init
    expire: 86400
    checkRefreshExpire: 43200
    header: token
  judge:
    token: voj-judge-token-init
  db:
    host: 172.20.0.3
    public-host: 172.20.0.3
    port: 3306
    name: voj
    username: root
    password: voj123456
  mail:
    ssl: true
    username: your_email_username
    password: your_email_password
    host: smtp.qq.com
    port: 465
  redis:
    host: 172.20.0.2
    port: 6379
    password:
  web-config:
    base-url: "https://voj.mobi"
    name: "Virtual Online Judge"
    short-name: "VOJ"
    description: "Virtual Online Judge"
    register: false
    problem: true
    training: true
    contest: true
    status: true
    rank: true
    discussion: true
    introduction: true
    code-visible-start-time: 1262275200000
    footer:
      record:
        name: your_website_record_number
        url: "https://beian.miit.gov.cn"
      project:
        name: "VOJ"
        url: "https://github.com/simplefanC/voj"