version: "3"
services:
  voj-judger:
    image: registry.cn-shanghai.aliyuncs.com/simplefanc/voj_judger
    container_name: voj-judger
    restart: always
    volumes:
      - ${VOJ_JUDGESERVER_DATA_DIRECTORY}/testcase:/judge/testcase
      - ${VOJ_JUDGESERVER_DATA_DIRECTORY}/log:/judge/log
      - ${VOJ_JUDGESERVER_DATA_DIRECTORY}/run:/judge/run
      - ${VOJ_JUDGESERVER_DATA_DIRECTORY}/spj:/judge/spj
      - ${VOJ_JUDGESERVER_DATA_DIRECTORY}/interactive:/judge/interactive
      - ${VOJ_JUDGESERVER_DATA_DIRECTORY}/voj-judger-1.0.jar:/judge/app.jar
    environment:
      - TZ=Asia/Shanghai
#      - JAVA_OPTS=-Xmx1G -Xms1G -XX:MaxMetaspaceSize=256M -XX:MetaspaceSize=256M
      - JUDGE_SERVER_IP=${JUDGE_SERVER_IP} # 服务器公网ip
      - JUDGE_SERVER_PORT=${JUDGE_SERVER_PORT:-8088}
      - JUDGE_SERVER_NAME=${JUDGE_SERVER_NAME} # 判题服务的名称，最好每个判题机不一样
      - NACOS_URL=${NACOS_HOST}:${NACOS_PORT}  # nacos所在服务的ip:port
      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}  # 分布式需要修正nacos账号密码
      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
      - MAX_TASK_NUM=${MAX_TASK_NUM:--1} # -1表示最大可接收判题任务数为cpu核心数+1
      - REMOTE_JUDGE_OPEN=${REMOTE_JUDGE_OPEN:-true} # 当前判题服务器是否开启远程虚拟判题功能
      - REMOTE_JUDGE_MAX_TASK_NUM=${REMOTE_JUDGE_MAX_TASK_NUM:--1} # -1表示最大可接收远程判题任务数为cpu核心数*2+1
      - PARALLEL_TASK=${PARALLEL_TASK:-default} # 默认沙盒并行判题程序数为cpu核心数
    ports:
      - ${JUDGE_SERVER_PORT:-8088}:${JUDGE_SERVER_PORT:-8088}
      # - "0.0.0.0:5050:5050" # 一般不开放安全沙盒端口
#    healthcheck:
#      test: curl -f http://localhost:${JUDGE_SERVER_PORT:-8088}/version || exit 1
#      interval: 30s
#      timeout: 10s
#      retries: 3
    shm_size: 512mb
    privileged: true # 设置容器的权限为root

  voj-rsync-slave:
    image: registry.cn-shanghai.aliyuncs.com/simplefanc/voj_rsync
    container_name: voj-rsync-slave
    restart: always
    volumes:
      - ${VOJ_JUDGESERVER_DATA_DIRECTORY}/testcase:/voj/testcase
      - ${VOJ_JUDGESERVER_DATA_DIRECTORY}/log:/voj/log
    environment:
      - RSYNC_MODE=slave # 当前为slave从服务
      - RSYNC_USER=vojrsync # 与主服务器的rsync的用户一致
      - RSYNC_PASSWORD=${RSYNC_PASSWORD} # 与主服务器的rsync密码一致
      - RSYNC_MASTER_ADDR=${RSYNC_MASTER_ADDR} # 写入主服务器ip
    ports:
      - "0.0.0.0:873:873"